spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/barberdb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com.bs.mrmf.mapper/*.xml
  type-aliases-package: com.bs.mrmf.pojo
